### ISSUE TITLE
release on fdroid

### ISSUE THREAD

**Issue by olumolu** [permissionlesstech/bitchat-android#38]
### Checklist

- [x] I have used the search function for [**OPEN**](https://github.com/callebtc/bitchat-android/issues) issues to see if someone else has already submitted the same feature request.
- [x] I have **also** used the search function for [**CLOSED**](https://github.com/callebtc/bitchat-android/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [x] I will describe the problem with as much detail as possible.
- [x] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

0.0.0

### Feature or improvement you want

Please add this app in fdroid

**Comment by rollingmoai** [comment]
- Perhaps #52 should be fixed first

**Comment by olumolu** [comment]
> * Perhaps [APK version does not match release version #52](https://github.com/permissionlesstech/bitchat-android/issues/52) should be fixed first

It will be fixed as fdroid build the app from source.

**Comment by IzzySoft** [comment]
> It will be fixed as fdroid build the app from source.

Not really fixed just by that build. It won't be a reproducible build then 😉 You should always build the APK from a clean tree at the commit the tag points to ("first basic rule" of our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers)). And not even apart from that, as the current HEAD still has `versionCode = 1` and `versionName = "1.0"`. 🤷‍♂️ 

What's more: with `versionCode` never being increased (we're talking about the 6th release here, and it's still set to `1`), updates will be impossible – as Android (and F-Droid, and IzzyOnDroid, and also PlayStore etc) use this to tell versions apart.

**Comment by LLEECCHH** [comment]
You can use [Obtainium | F-Droid](https://f-droid.org/packages/dev.imranr.obtainium.fdroid/) to download apks directly from the repo's releses page with automatic update checks.

**Comment by bi4key** [comment]
> You can use [Obtainium | F-Droid](https://f-droid.org/packages/dev.imranr.obtainium.fdroid/) to download apks directly from the repo's releses page with automatic update checks.

Or use fork "Discoverium" to have some new features.

https://github.com/cygnusx-1-org/Discoverium/

**Comment by ghost** [comment]
Yes, I agree that being on f-droid is a great guarantee that it's really foss.

**Comment by Jacques-Olivier-Farcy** [comment]
I hope i will be able to install and update bitchat via Fdroid

**Comment by UjuiUjuMandan** [comment]
Current block for F-Droid inclusion is GMS location dependency, 

* https://github.com/permissionlesstech/bitchat-android/pull/264#issuecomment-3536814510

probably there should be a fdroid flavor not include that?

**Comment by missaustraliana** [comment]
https://github.com/permissionlesstech/bitchat-android/pull/633

if this were to be merged, this would get it on f-droid

**Comment by pixel2user** [comment]
I can't believe this app still isn't available on F-Droid!

"Bitchat has become the most downloaded app in Uganda amid a government-ordered nationwide internet shutdown."

"F-Droid Nearby is a simple app for exchanging free software apps locally, device-to-device, even when internet is not available or too expensive. It is compatible with the built-in Nearby feature of the F-Droid client app."

**Comment by ElonSatoshi** [comment]
If anyone finds this via searching, you can use Localsend to share any installed app offline

**Comment by nutpantz** [comment]
support open source and publish on fdroid or https://apt.izzysoft.de/fdroid/
google is trying to strangle open source software on android.
https://keepandroidopen.org/
