### ISSUE TITLE
/w listing users by ID rather than nickname

### ISSUE THREAD

**Issue by Nikorasu** [permissionlesstech/bitchat-android#46]
Not sure if this should be reported here, or for the iOS version.. But I'm using this version. (0.5.1 on a Samsung Galaxy A25)

When I use the /w command, it responds with a list of user IDs like "a2d7ec11" rather than a list of the names that show as they chat. I assume that's not the way it's intended to be?

**Comment by moehamade** [comment]
This is working as of version 0.7 please close this issue @Nikorasu

**Comment by Nikorasu** [comment]
> This is working as of version 0.7 please close this issue [@Nikorasu](https://github.com/Nikorasu)

No it's not? I'm on 0.7 right now. When I type the /w command it's still responding with some ID, rather than nicknames:
> [23:58:19] * online users: 733d32e4 *

When I tap on the User-Count in the upper right corner, the Your Network list does show the nicknames correctly there tho.

**Comment by moehamade** [comment]
@Nikorasu 
This was fixed on main branch, and main branch is already version 0.7, did you download the APK from official Github Repo? If yes, then just wait for next build and this issue should be fixed, I tested it myself and we are already displaying nicknames instead of IDs.
<img width="881" height="455" alt="Image" src="https://github.com/user-attachments/assets/6f819840-b80a-4928-b355-5e81d3f9d0ca" />

**Comment by Nikorasu** [comment]
Okay, well I'll close it, since seems like it's being addressed either way. Thanks for the heads up!

**Comment by Nikorasu** [comment]
I am still seeing this issue on 0.7.2:
![Image](https://github.com/user-attachments/assets/4f05814a-4c43-4cbd-83df-9347b2f580b3)
_TYPING_ /w does not list nicknames right. However, tapping the connection number in the upper right, does.
